// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.Text.Json.Serialization;

namespace EnviosWebApi.Models;

public partial class TEnvio
{
    public int Codigo { get; set; }

    public DateTime FechaEnvio { get; set; }

    public string Direccion { get; set; }

    public string Estado { get; set; }

    public string DniCliente { get; set; }

    public int IdEmpresa { get; set; }

    [JsonIgnore]
    public virtual TEmpresa IdEmpresaNavigation { get; set; }
}